apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
        - name: mysql
          image: mysql-server-customer-api:latest
          ports:
            - containerPort: 3306


  #Remove this: kubectl delete deployment mysql-deployment